name: Pre-Install

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'  # Configura o Ruby na versão 2.7
      # O Fastlane é uma ferramenta escrita em Ruby, então precisamos garantir que uma versão compatível do Ruby esteja instalada.

    - name: Install Fastlane
      run: gem install fastlane  # Instala o Fastlane, uma ferramenta para automação de deploys