name: Pre-Install Workflow

on:
  workflow_call:  # Permite que este workflow seja chamado por outro workflow

jobs:
  preinstall:
    runs-on: ubuntu-latest  # Pode rodar em um ambiente Ubuntu ou macOS (dependendo do seu uso)

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'  # Configura o Ruby na versão 3.0.0
        # O Fastlane é uma ferramenta escrita em Ruby, então precisamos garantir que uma versão compatível do Ruby esteja instalada.

      - name: Install Fastlane
        run: gem install fastlane  # Instala o Fastlane, uma ferramenta para automação de deploys
